### ISSUE TITLE
app-springboot test fails

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak-quickstarts#378]
### Describe the bug

Tests fails. After some investigation the issue is seems to be in missing running springboot rest service.
https://github.com/keycloak/keycloak-quickstarts/blob/latest/scripts/run-tests.sh#L94

```
Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 8.182 sec <<< FAILURE! - in org.keycloak.quickstart.springboot.ProductAppTest
testLogin(org.keycloak.quickstart.springboot.ProductAppTest)  Time elapsed: 2.293 sec  <<< ERROR!
com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 500  for http://localhost:8080/products
	at org.keycloak.quickstart.springboot.ProductAppTest.testLogin(ProductAppTest.java:63)

testLogout(org.keycloak.quickstart.springboot.ProductAppTest)  Time elapsed: 1.001 sec  <<< ERROR!
com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 500  for http://localhost:8080/products
	at org.keycloak.quickstart.springboot.ProductAppTest.testLogout(ProductAppTest.java:72)


Results :

Tests in error: 
  ProductAppTest.testLogin:63 » FailingHttpStatusCode 500  for http://localhost:...
  ProductAppTest.testLogout:72 » FailingHttpStatusCode 500  for http://localhost...

Tests run: 3, Failures: 0, Errors: 2, Skipped: 0
```

### Version

n/a

**Comment by ikhomyn** [comment]
Fixed in https://github.com/keycloak/keycloak-quickstarts/pull/386
