### ISSUE TITLE
Jakarta Saml QS - outdated dependencies 

### ISSUE THREAD

**Issue by lhanusov** [keycloak/keycloak-quickstarts#472]
### Describe the bug

SAML jsp doesn't work with Wildfly 23 -> missing latest Jakarta JSP library:
* https://github.com/keycloak/keycloak-quickstarts/blob/latest/jakarta/servlet-saml-service-provider/src/main/webapp/index.jsp
* error: org.apache.jasper.JasperException: JBWEB004036: File "jakarta.tags.core" not found

This adapter doesn't work with latest Wildfly (version 29) - missing org.picketbox library:
* SAML: https://github.com/keycloak/keycloak-quickstarts/tree/latest/jakarta/servlet-saml-service-provider#starting-the-wildfly-server

### Version

latest

### Expected behavior

Application should display login page: http://localhost:8080/servlet-saml-service-provider/

### Actual behavior

Gets error:

Context Path:/servlet-saml-service-provider
Servlet Path:/index.jsp
Path Info:null
Query String:null
Stack Trace:
org.apache.jasper.JasperException: JBWEB004036: File "jakarta.tags.core" not found
	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:57)
	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:278)
	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:75)
	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:176)
	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:412)
	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.compiler.Parser.parseDirective(Parser.java:475)
	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.compiler.Parser.parseElements(Parser.java:1462)
	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.compiler.Parser.parse(Parser.java:143)

### How to Reproduce?

* download wildfly 23
* install keycloak saml adapter
* deploy saml war
* open application url: http://localhost:8080/servlet-saml-service-provider/

**Comment by lhanusov** [comment]
@pedroigor once you are back from PTO, please can you ping me to discuss this issue? thank you

**Comment by pedroigor** [comment]
@lhanusov Hey. Just run the quickstart tests using 29.0.1.Final and they pass. What do you have in mind?

**Comment by pedroigor** [comment]
It should be fixed now we have upgraded the SAML adapter to work with the latest Wildfly versions and Jakarta. See the example at https://github.com/keycloak/keycloak-quickstarts/tree/latest/jakarta/servlet-saml-service-provider.
