### ISSUE TITLE
Jakarta tests are failing with latest main

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak-quickstarts#595]
### Describe the bug

It is failing with something like the exception below. Likely caused by https://github.com/keycloak/keycloak/commit/dad4477995de9c4955eab1f5d73d92680e90056d :

```
 04:06:06,045 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 50) MSC000001: Failed to start service jboss.deployment.unit."servlet-saml-service-provider.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.unit."servlet-saml-service-provider.war".undertow-deployment: java.lang.ExceptionInInitializerError
	at org.wildfly.extension.undertow@29.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:90)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: java.lang.ExceptionInInitializerError
	at org.keycloak.keycloak-saml-adapter-core@999.0.0-SNAPSHOT//org.keycloak.adapters.saml.config.PemUtils.decodePrivateKey(PemUtils.java:127)
	at org.keycloak.keycloak-saml-adapter-core@999.0.0-SNAPSHOT//org.keycloak.adapters.saml.config.PemUtils.decodePrivateKey(PemUtils.java:101)
	at org.keycloak.keycloak-saml-adapter-core@999.0.0-SNAPSHOT//org.keycloak.adapters.saml.config.parsers.DeploymentBuilder.build(DeploymentBuilder.java:127)
	at org.keycloak.keycloak-saml-wildfly-elytron-adapter@999.0.0-SNAPSHOT//org.keycloak.adapters.saml.elytron.KeycloakConfigurationServletListener.contextInitialized(KeycloakConfigurationServletListener.java:101)
	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:219)
	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:187)
	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
```

### Version

nightly from 2024-09-09 (maybe earlier)

**Comment by mposolda** [comment]
This is caused by the Keycloak issue https://github.com/keycloak/keycloak/issues/32817 . Due to that, the SAML quickstart is not able to deploy.

Once that issue is fixed in Keycloak, then this quickstart issue will be probably "autofixed" during the next nightly run.

**Comment by mposolda** [comment]
Closing as the update to Keycloak server with fixed https://github.com/keycloak/keycloak/issues/32817 just fixed this.
